name: Deploy a Nomad Job
description: Deploys a HCL nomad job
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  token:
    description: 'Authentication token'
    required: true
  job:
    description: 'Path to the job file'
    required: true
  endpoint:
    description: 'Endpoint to submit the job'
    required: true

runs:
  using: "composite"
  steps:
    - name: Submit Job
      shell: bash
      run: |
        curl -X POST \
          -H "X-API-Key: ${{ inputs.token }}" \
          -H "Content-Type: text/plain" \
          --data-binary "@${{ inputs.job }}" \
          "${{ inputs.endpoint}}"
